package colas;

import java.text.DecimalFormat;

/**
 *
 * @author onefr
 */
public class Colas extends javax.swing.JFrame {

    public Colas() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public double y() {

        double prom = Double.parseDouble(jT_n.getText()) / Double.parseDouble(jT_tiempo.getText());
        return prom;
    }

    public double u() {
        double at = Double.parseDouble(jT_atencion.getText()) / Double.parseDouble(jT_tiempo.getText());
        return at;
    }

    public double p() {
        double v = y() / u();
        return v;
    }

    public double ls() {
        double ls = (y()) / (u() - y());
        return ls;
    }

    public double ws() {
        double ws = ls() / y();
        return ws;
    }

    public double lq() {
        double lq = (y() / u()) * ls();
        return lq;
    }

    public double wq() {
        double wq = lq() / y();
        return wq;
    }

    public double nEle() {
        double proba = 0;
        try {
            proba = (1 - (y() / u())) * Math.pow((y() / u()), Double.parseDouble(jT_nEle.getText()));
        } catch (Exception e) {
            return 0.0;
        }
        return proba;
    }

    public String sin() {
        double sin = (1 - p()) * 100;
        return sin + " %";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jL_titulo = new javax.swing.JLabel();
        jP_c1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jT_n = new javax.swing.JTextField();
        jT_atencion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jT_LQ = new javax.swing.JTextField();
        jT_Y = new javax.swing.JTextField();
        jT_U = new javax.swing.JTextField();
        jT_P = new javax.swing.JTextField();
        jT_LS = new javax.swing.JTextField();
        jT_WS = new javax.swing.JTextField();
        jT_WQ = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jT_0 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jT_tiempo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jT_nEle = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jL_ProbabiN = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jL_titulo.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jL_titulo.setText("Colas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jL_titulo)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jL_titulo)
                .addGap(209, 209, 209))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 490));

        jP_c1.setBackground(new java.awt.Color(204, 204, 204));
        jP_c1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        jLabel1.setText("Promedio de N elementos:");
        jP_c1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 32, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        jLabel2.setText("Capacidad de atencion:");
        jP_c1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jP_c1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jP_c1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 100, 14));

        jT_n.setBackground(new java.awt.Color(255, 255, 103));
        jT_n.setBorder(null);
        jP_c1.add(jT_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jT_atencion.setBackground(new java.awt.Color(255, 255, 103));
        jT_atencion.setBorder(null);
        jT_atencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_atencionActionPerformed(evt);
            }
        });
        jP_c1.add(jT_atencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 189, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel4.setText("LQ:");
        jP_c1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 30, 20));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel5.setText("Y:");
        jP_c1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 20, 20));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel6.setText("U:");
        jP_c1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 20, 20));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel7.setText("P:");
        jP_c1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 20, 20));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel8.setText("LS:");
        jP_c1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 30, 25));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel9.setText("WS:");
        jP_c1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 30, 20));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel10.setText("WQ:");
        jP_c1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 30, 20));

        jT_LQ.setBorder(null);
        jP_c1.add(jT_LQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 110, -1));

        jT_Y.setBorder(null);
        jP_c1.add(jT_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, -1));

        jT_U.setBorder(null);
        jP_c1.add(jT_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, -1));

        jT_P.setBorder(null);
        jP_c1.add(jT_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 120, -1));

        jT_LS.setBorder(null);
        jP_c1.add(jT_LS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 120, -1));

        jT_WS.setBorder(null);
        jP_c1.add(jT_WS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, -1));

        jT_WQ.setBorder(null);
        jP_c1.add(jT_WQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jP_c1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Media de llegada por Hora =");
        jP_c1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 160, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setText("Media de servicio o Atencion =");
        jP_c1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setText("Probabilidad =");
        jP_c1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setText("Numero de promedio en la cola =");
        jP_c1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel14.setText("Tiempo de Espera en el sistema =");
        jP_c1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel15.setText("Tiempo de espera en la cola =");
        jP_c1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 170, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel16.setText("Timepo promedio en el sistema =");
        jP_c1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 190, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setText("Probabilidad de que el Sistema este vacio =");
        jP_c1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 250, 20));

        jT_0.setBorder(null);
        jP_c1.add(jT_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 90, -1));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        jLabel18.setText("Tiempo (minutos):");
        jP_c1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jT_tiempo.setBackground(new java.awt.Color(255, 255, 103));
        jT_tiempo.setBorder(null);
        jP_c1.add(jT_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 100, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jP_c1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 189, 14));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel20.setText("Probabilidad de que haya N elementos en la cola =");
        jP_c1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 290, -1));

        jT_nEle.setBackground(new java.awt.Color(255, 255, 103));
        jT_nEle.setBorder(null);
        jP_c1.add(jT_nEle, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 40, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setText("Elementos en cola para calcular:");
        jP_c1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jL_ProbabiN.setText("0%");
        jP_c1.add(jL_ProbabiN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel19.setText("Probabilidad de que el Sistema este vacio =");
        jP_c1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 250, 20));

        jPanel1.add(jP_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 680, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DecimalFormat decimal = new DecimalFormat("#.###");
        //jT_Y.setText(decimal.format(Double.parseDouble(jT_n.getText()) / Double.parseDouble(jT_tiempo.getText())));
        jT_Y.setText(decimal.format(y()));
        jT_U.setText(decimal.format((Double.parseDouble(jT_atencion.getText()) / Double.parseDouble(jT_tiempo.getText()))));
        jT_P.setText(decimal.format((p() * 100)) + " %");
        jT_LS.setText(decimal.format(ls()));
        jT_WS.setText(decimal.format(ws()));
        jL_ProbabiN.setText(decimal.format((nEle() * 100)) + " %");
        if (Integer.parseInt(jT_n.getText()) > Integer.parseInt(jT_atencion.getText())) {
            jT_WQ.setText(decimal.format(wq()));

        } else {
            //jT_WQ.setText(decimal.format(u()));
        }

        jT_LQ.setText(decimal.format(lq()));
        jT_0.setText(sin());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jT_atencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_atencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_atencionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL_ProbabiN;
    private javax.swing.JLabel jL_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jP_c1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jT_0;
    private javax.swing.JTextField jT_LQ;
    private javax.swing.JTextField jT_LS;
    private javax.swing.JTextField jT_P;
    private javax.swing.JTextField jT_U;
    private javax.swing.JTextField jT_WQ;
    private javax.swing.JTextField jT_WS;
    private javax.swing.JTextField jT_Y;
    private javax.swing.JTextField jT_atencion;
    private javax.swing.JTextField jT_n;
    private javax.swing.JTextField jT_nEle;
    private javax.swing.JTextField jT_tiempo;
    // End of variables declaration//GEN-END:variables

}
